### ISSUE TITLE
No Project

### ISSUE THREAD

**Issue by alessandrror** [GOES-Academy/DouglasEmestica-mi-proyecto-npm#1]
Falta el proyecto aún, solo está el repositorio.

Tú puedes Douglas, don't be like Andrés, un pajero

**Comment by noe-cortez-dev** [comment]
Te recomiendo que te leas la documentacion de [vite](https://vitejs.dev/).

**Comment by alessandro-rivas-dev** [comment]
> Te recomiendo que te leas la documentacion de [vite](https://vitejs.dev/).

👀 Ojito, @douglas-emestica-dev, eso te va a encantar.
